#Clean workspace

```{r}
# Clear plots
if(!is.null(dev.list())) dev.off()


# Clean workspace
rm(list=ls())
```


#Row selection
```{r}
path <- "path.txt"
path <- readChar(path, file.info(path)$size)
setwd(path) #set the working directory
df <- read.delim("All_GPUs.csv",sep = ',',header=T);
var_numericas <- c("Core_Speed", "L2_Cache", "Max_Power", "Memory", "Memory_Bandwidth", "Memory_Speed", "TMUs", "Texture_Rate")
var_binarias <- c("Dedicated", "Notebook_GPU", "SLI_Crossfire");
var_cualitativas <- c("Direct_X","Architecture", "Manufacturer", "Memory_Type", "Open_GL", "Shader", "Memory_Bus", "Name", "Resolution_WxH", "Release_Date")
vars <- c(var_numericas, var_binarias, var_cualitativas)
df

```


```{r}
df <- read.delim("All_GPUs.csv",sep = ',',header=T);
df[var_numericas]$Max_Power <- sub(" Watts", "", df[var_numericas]$Max_Power)
df[var_numericas]$L2_Cache <- sub("KB", "", df[var_numericas]$L2_Cache)
df[var_numericas]$L2_Cache <- as.numeric(df[var_numericas]$L2_Cache)
df[var_numericas]$Max_Power <- as.numeric(df[var_numericas]$Max_Power)
df[var_numericas]$Core_Speed <- sub(" MHz", "", df[var_numericas]$Core_Speed)
df$Core_Speed <- as.numeric(as.character(df$Core_Speed))
df[var_numericas]$Memory_Bandwidth <- sub("GB/sec", "", df[var_numericas]$Memory_Bandwidth)
df[var_numericas]$Memory_Bandwidth <- as.numeric(df[var_numericas]$Memory_Bandwidth)
df[var_numericas]$Memory <- sub(" MB", "", df[var_numericas]$Memory)
df[var_numericas]$Memory <- as.numeric(df[var_numericas]$Memory)
df[var_numericas]$Memory_Speed <- sub(" MHz", "", df[var_numericas]$Memory_Speed)
df[var_numericas]$Memory_Speed <- as.numeric(df[var_numericas]$Memory_Speed)
df[var_numericas]$Texture_Rate <- sub(" GTexel/s", "", df[var_numericas]$Texture_Rate)
df[var_numericas]$Texture_Rate <- as.numeric(df[var_numericas]$Texture_Rate)

```


```{r}
df[var_cualitativas]$Memory_Bus <- sub(" Bit", "", df[var_cualitativas]$Memory_Bus)
df[var_cualitativas]$Direct_X <- sub("DX ", "", df[var_cualitativas]$Direct_X)
df[var_cualitativas]$Open_GL <- as.factor(df[var_cualitativas]$Open_GL)
df[var_cualitativas]$Shader <- as.factor(df[var_cualitativas]$Shader)
df[var_cualitativas]$Direct_X <- gsub("*\\.[0]+", "", df[var_cualitativas]$Direct_X)
df[var_cualitativas]$Direct_X <- as.factor(df[var_cualitativas]$Direct_X)
df[var_cualitativas]$Release_Date <- sub("\n", "", df[var_cualitativas]$Release_Date)
df[var_cualitativas]$Release_Date <- gsub(" ", "", df[var_cualitativas]$Release_Date)
```


```{r}
df[var_binarias]$Dedicated <- df[var_binarias]$Dedicated == "Yes"
df[var_binarias]$Notebook_GPU <- df[var_binarias]$Notebook_GPU == "Yes" 
df[var_binarias]$SLI_Crossfire <- df[var_binarias]$SLI_Crossfire == "Yes" 
df[var_binarias]
```

```{r}
all <- c(var_cualitativas, var_numericas, var_binarias)
df_selected <- df[all]
df_selected[df_selected==""] <- NA
df_clean <- na.omit(df_selected)
```

```{r}
write.csv(df_selected, "clean_table.csv", row.names = FALSE)
```



