#Retrieve the data saved AFTER the profiling practice...... this means data already cleaned

```{r}
# install.packages('cluster')
path <- "path.txt"
path <- readChar(path, file.info(path)$size)
path <- gsub("[\r\n]", "", path)
setwd(path) #set the working directory
df <- read.delim("clean_table_knn.csv",sep = ',',header=T);
df

borrar <- c("group_mPower","group_cSpeed", "group_mSpeed")
df <- df[ , !(names(df) %in% borrar)]
df

var_binarias <- c("Dedicated", "Notebook_GPU", "SLI_Crossfire")
var_cualitativas <- c("Direct_X","Architecture", "Manufacturer", "Memory_Type", "Open_GL", "Shader", "Name", "Resolution_WxH", "Release_Date", "Memory_Bus")


for (i in var_cualitativas){ 
    df[,i] <- as.factor(df[,i])
}

for (i in var_binarias){ 
    df[,i] <- as.factor(df[,i]) 
}
df



```

# HIERARCHICAL CLUSTERING
```{r}
library('cluster')
numericalVariables <- lapply(df, is.numeric)
dfNum<-df[,unlist(numericalVariables)]
dfNum

d  <- dist(dfNum)
h1 <- hclust(d,method="ward.D")  # NOTICE THE COST
plot(h1)

```



# BUT WE ONLY NEED WHERE THERE ARE THE LEAPS OF THE HEIGHT

# WHERE ARE THER THE LEAPS? WHERE WILL YOU CUT THE DENDREOGRAM?, HOW MANY CLASSES WILL YOU OBTAIN?

```{r}
nc = 2

c1 <- cutree(h1,nc)

table(c1)

cdg <- aggregate(as.data.frame(dfNum),list(c1),mean)
cdg

plot(cdg[,1], cdg[,7])
``` 

# LETS SEE THE PARTITION VISUALLY

```{r}

plot(df$Memory,df$Memory_Bandwidth,col=c1,main="Clustering of credit data in 3 classes")
legend("topright",c("class1","class2","class3"),pch=1,col=c(1:3))

#plot(RatiFin,Estalvi)
#plot(RatiFin,Estalvi,col=c1,main="Clustering of credit data in 3 classes")
#legend("topright",c("class1","class2","class3"),pch=1,col=c(1:3), cex=0.6)


df
pairs(df[,1:9], col=c1)

```

```{r}
# move to Gower mixed distance to deal 
# simoultaneously with numerical and qualitative data
borrar <- c("Release_Date", "Name")
df2 <- df[ , !(names(df) %in% borrar)]


dissimMatrix <- daisy(df2, metric = "gower", stand=TRUE)

distMatrix<-dissimMatrix^2

h2 <- hclust(distMatrix,method="ward.D")  # NOTICE THE COST
plot(h2)


c2 <- cutree(h2,4)

#class sizes 
table(c2)

#comparing with other partitions
table(c1,c2)

df2
pairs(df2[,8:12], col=c2)

```


