#  READING CREDSCO.CSV. NOTE: Change the path of the file for the proper one in your computer

#Note: Take care to use "/" fo the directory file. "\" provides errors


#Clean workspace

```{r}
# Clear plots
if(!is.null(dev.list())) dev.off()


# Clean workspace
rm(list=ls())
```

```{r}
path <- "path.txt"
path <- readChar(path, file.info(path)$size)
setwd(path) #set the working directory
# setwd("C:/Users/Daniel Cano/Desktop/MD/D2") #set the working directory

dd <- read.table("clean_table.csv",header=T, sep=",");

dd
```


```{r}
#start substituting the structural missing values.
#with remaining, impute: Knn, MIMMI, MICE (multiple imputation, only if you know well)

# IMPUTATION By THE 1NN

library(class)

# FOR EVERY INDIVIDUAL WITH MISSING Incomes LOOK FOR THE MOST SIMILAR INDIVIDUAL 
# wrt REMAINING VARIABLES AND COPY THE VALUE OF INGRESSOS ON THE FIRST 
#For more robustness average the values of k-NN in general (with small k)


# For a single variable:
# Build an artificial matrix with the full numerical variables

dd_num_orig <- data.frame(x1 = 1:dim(dd)[1])
for (J in names(dd)) {
  if (is.numeric(dd[,J][0])) {
    dd_num_orig[J] <- dd[,J]
  }
}


drops <- c("x1", "Open_GL", "Shader")
dd_num <- dd_num_orig[ , !(names(dd_num_orig) %in% drops)]



dd_num_nulls <- dd_num
dd_num <- dd_num[complete.cases(dd_num[, 1:dim(dd_num)[2]]),]

```


```{r}
elem_f <- c()
elem_nf <- c()

nombres_tabla <- names(dd_num_nulls)

for (k in 1:length(dd_num_nulls)) {
  v <- dd_num_nulls[,k]
  if (sum(is.na(v)) > 0) elem_nf <- c(nombres_tabla[k], elem_nf)
  else elem_f <- c(nombres_tabla[k], elem_f)
}

escalar <- c("Core_Speed", "L2_Cache", "Max_Power", "Memory", "Memory_Speed", "TMUs", "Texture_Rate", "Memory_Bandwidth")
exponential <- c("L2_Cache", "Max_Power", "Memory", "Memory_Bandwidth", "TMUs", "Texture_Rate")

dd_num_nulls_pre <- dd_num_nulls

for (k in elem_nf){
  #faltan <- dd_num_nulls[is.na(dd_num_nulls[,k]), -k]
  faltan <- dd_num_nulls[is.na(dd_num_nulls[,k]),]
  faltan <- faltan[,!(names(faltan) %in% k)]
  nombres <- c()
  
  for (n in elem_f) {
    #nombres <- c(nombres, nombres_tabla[n])
    nombres <- c(nombres, n)
  }
  
  faltan <- faltan[, nombres]
  
  
  
  nombres <- c(nombres, k)
  tengo <- dd_num_nulls[!is.na(dd_num_nulls[,k]), nombres]
  
  
  tengo_datos <- tengo[, !(names(tengo) %in% k)]
  tengo_resultados <- tengo[, k]
  
  
  knn.values = knn(tengo_datos, faltan, tengo_resultados)
  
  
  
  
  
  dd_num_nulls[is.na(dd_num_nulls[,k]), k] = as.numeric(as.character(knn.values))
  
  elem_f<-c(elem_f, elem_nf[1])
  if (length(elem_nf) > 1) {
    #elem_nf <- c(elem_nf[2]:elem_nf[length(elem_nf)])
    long <- length(elem_nf)
    elem_nf <- c(elem_nf[2:long])
  }
  

}


for (k in names(dd)) {
  if (!(k %in% names(dd_num_nulls))) {
    dd_num_nulls[k] = dd[,k]
  }
}

dd_num_nulls$group_mBand = cut(as.integer(dd_num_nulls$Memory_Bandwidth), c(0,32,128,512,1024,2048))
dd_num_nulls$group_l2 = cut(dd_num_nulls$L2_Cache, c(0,128,256,512,768,1024,2048,4069))
dd_num_nulls$group_mem = cut(dd_num_nulls$Memory, c(0,256,1024,4069,16384,32768))
dd_num_nulls$group_TMUs = cut(dd_num_nulls$TMUs, c(0,25,50,75,100,125,150,175,200,225,250,275,300,450))
dd_num_nulls$group_mPower = cut(dd_num_nulls$Max_Power, c(0,400,800))
dd_num_nulls$group_cSpeed = cut(dd_num_nulls$Core_Speed, c(0, 500, 1000, 1500, 2000, 2500))
dd_num_nulls$group_mSpeed = cut(dd_num_nulls$Memory_Speed, c(0, 64, 256, 1024, 4096))


for (k in exponential) {
    dd_num_nulls[, k] <- log(dd_num_nulls[, k])
}

for (k in escalar) {
    #dd_num_nulls[, k] <- scale(dd_num_nulls[, k])
}






transformed <- names(dd_num_nulls)

for (n in transformed) {
  if (is.numeric(dd_num_nulls[1,n])) {
    hist(dd_num_nulls[,n], main=paste("After KNN ", n) , xlab="Post")
    hist(dd_num_nulls_pre[,n], main=paste("Before KNN " , n) )
  }
}


write.csv(dd_num_nulls, "clean_table_knn.csv", row.names = FALSE)


```

```{r}
hist(log(dd_num_nulls$L2_Cache))
hist(scale(dd_num_nulls$Memory_Speed))
#hist(scale(log(dd_num_nulls$Memory_Bandwidth)))
```
```{r}
#install.packages("EnvStats")
library(EnvStats)
r <- eexp(dd_num_nulls$Memory_Bandwidth)[3]$parameters
r
```


```{r}

u = 1 - exp(r*dd_num_nulls$Memory_Bandwidth)
qnorm(u)
hist(qnorm(u)) 
```



