
#Clean workspace

```{r}
# Clear plots
if(!is.null(dev.list())) dev.off()


# Clean workspace
rm(list=ls())
```

#Row selection
```{r}
setwd("C:/Users/edu11/Desktop/UNI/MD/MD-master/D2") #set the working directory
df <- read.delim("All_GPUs.csv",sep = ',',header=T);
names(df)
var_numericas <- c("Core_Speed", "L2_Cache", "Max_Power", "Memory", "Memory_Bandwidth", "Memory_Speed", "TMUs", "Texture_Rate")#, "Release_Date")
var_binarias <- c("Dedicated", "Notebook_GPU", "SLI_Crossfire");
var_cualitativas <- c("Direct_X","Architecture", "Manufacturer", "Memory_Type", "Open_GL", "Shader", "Memory_Bus", "Name", "Resolution_WxH")
vars <- c(var_numericas, var_binarias, var_cualitativas)
set.seed(28061963)
sam<-as.vector(sort(sample(1:nrow(df),2000)))
df_final <- df[sam,vars]
summary(df_final)

```





```{r}
df <- read.delim("All_GPUs.csv",sep = ',',header=T);
df[var_numericas]$Max_Power <- sub(" Watts", "", df[var_numericas]$Max_Power)
df[var_numericas]$L2_Cache <- sub("KB", "", df[var_numericas]$L2_Cache)
df[var_numericas]$L2_Cache <- as.numeric(df[var_numericas]$L2_Cache)
df[var_numericas]$Max_Power <- as.numeric(df[var_numericas]$Max_Power)
df[var_numericas]$Core_Speed <- sub(" MHz", "", df[var_numericas]$Core_Speed)
df$Core_Speed <- as.numeric(as.character(df$Core_Speed))
df[var_numericas]$Memory_Bandwidth <- sub("GB/sec", "", df[var_numericas]$Memory_Bandwidth)
df[var_numericas]$Memory_Bandwidth <- as.numeric(df[var_numericas]$Memory_Bandwidth)
df[var_numericas]$Memory <- sub(" MB", "", df[var_numericas]$Memory)
df[var_numericas]$Memory <- as.numeric(df[var_numericas]$Memory)
df[var_numericas]$Memory_Speed <- sub(" MHz", "", df[var_numericas]$Memory_Speed)
df[var_numericas]$Memory_Speed <- as.numeric(df[var_numericas]$Memory_Speed)
df[var_numericas]$Texture_Rate <- sub(" GTexel/s", "", df[var_numericas]$Texture_Rate)
df[var_numericas]$Texture_Rate <- as.numeric(df[var_numericas]$Texture_Rate)

```


```{r}
df[var_cualitativas]$Memory_Bus <- sub(" Bit", "", df[var_cualitativas]$Memory_Bus)
df[var_cualitativas]$Direct_X <- sub("DX ", "", df[var_cualitativas]$Direct_X)
df[var_cualitativas]$Open_GL <- as.factor(df[var_cualitativas]$Open_GL)
df[var_cualitativas]$Shader <- as.factor(df[var_cualitativas]$Shader)
df[var_cualitativas]$Direct_X <- as.factor(df[var_cualitativas]$Direct_X)
df[var_cualitativas]$Memory_Bus <-as.factor(df[var_cualitativas]$Memory_Bus)

```


```{r}
df[var_binarias]$Dedicated <- df[var_binarias]$Dedicated == "Yes"
df[var_binarias]$Notebook_GPU <- df[var_binarias]$Notebook_GPU == "Yes" 
df[var_binarias]$SLI_Crossfire <- df[var_binarias]$SLI_Crossfire == "Yes" 
df[var_binarias]
```

```{r}
all <- c(var_cualitativas, var_numericas, var_binarias)
df_selected <- df[all]
df_selected[df_selected==""] <- NA
```







#Outliers treatment
```{r}
calcQ <- function(x) {
  s.x <- summary(x)
  iqr<-s.x[5]-s.x[2]
  list(souti=s.x[2]-3*iqr, mouti=s.x[2]-1.5*iqr, min=s.x[1], q1=s.x[2], q2=s.x[3], 
       q3=s.x[5], max=s.x[6], mouts=s.x[5]+1.5*iqr, souts=s.x[5]+3*iqr ) }

```

```{r}

var_numericas <-var_numericas[1:8]
for (i in var_numericas){
    Q <- calcQ(df_selected[,i])
    l <- which((df_selected$Core_Speed>Q$souts) || (df_selected$Core_Speed<Q$souti) || (df_selected$Core_Speed<0))
    df[l, i] <- NA
}
```


# imputar numericas
```{r}
summary(df_selected[,var_numericas])

library (missMDA)

impn<-imputePCA(df_selected[,var_numericas])

summary(df_selected[,var_numericas]) # Before
summary(impn$completeObs[,var_numericas]) # After

df_selected[,var_numericas] <- impn$completeObs[,var_numericas]
```

#imputar cualitativas

```{r}
summary(df_selected[,var_cualitativas])
vars_cual_miss<-var_cualitativas[c(1:7,9)] #aqui poner las que tienen missings

impc<-imputeMCA(df_selected[,vars_cual_miss])

summary(df_selected[,vars_cual_miss]) # Before
summary(impc$completeObs[,vars_cual_miss]) # After

df_selected[,vars_cual_miss] <- impc$completeObs[,vars_cual_miss]
```



