#Retrieve the data saved AFTER the profiling practice...... this means data already cleaned

```{r}
# Clear plots
if(!is.null(dev.list())) dev.off()


# Clean workspace
rm(list=ls())
```

```{r}
# install.packages('cluster')
path <- "path.txt"
path <- readChar(path, file.info(path)$size)
path <- gsub("[\r\n]", "", path)
setwd(path) #set the working directory
path
df <- read.delim("clean_table_knn.csv",sep = ',',header=T);
df

var_binarias <- c("Dedicated", "Notebook_GPU", "SLI_Crossfire")
var_cualitativas <- c("Direct_X","Architecture", "Manufacturer", "Memory_Type", "Open_GL", "Shader", "Name", "Resolution_WxH", "Release_Date", "Memory_Bus")


for (i in var_cualitativas){ 
    df[,i] <- as.factor(df[,i])
}

for (i in var_binarias){ 
    df[,i] <- as.factor(df[,i]) 
}
df

borrar <- c("group_mPower","group_cSpeed", "group_mSpeed", "group_mBand", "group_l2", "group_mem", "group_TMUs","Release_Date", "Name")
df <- df[ , !(names(df) %in% borrar)]
df


```



```{r}

if (!require('dendextend')) install.packages('dendextend'); library('dendextend')
library('cluster')
borrar <- c("Release_Date", "Name")
df2 <- df[ , !(names(df) %in% borrar)]



dissimMatrix <- daisy(df2, metric = "gower", stand=TRUE)

distMatrix<-dissimMatrix^2

dend <- as.dendrogram(hclust(distMatrix,method="ward.D"))

d1=color_branches(dend,k=4)

plot(d1)


c2 <- cutree(dend,4)

#class sizes 
table(c2)

df2
pairs(df2[,1:10], col=c2)

```


